config/routes.rb
Rails.application.routes.draw do

  get 'sessions/create'

  get 'sessions/destroy'

  resources :cards

  root 'cards#index'

  match '/votes', to: 'votes#create', via: :post

  get '/business' => 'high_voltage/pages#show', id: 'business'
  get '/design' => 'high_voltage/pages#show', id: 'design'
  get '/development' => 'high_voltage/pages#show', id: 'development'
  get '/growth' => 'high_voltage/pages#show', id: 'growth'
  get '/all', to:redirect('/')

  get 'feed/development'
  get 'feed/design'
  get 'feed/business'
  get 'feed/growth'
  get '/feed', to:redirect('/')

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/models/card.rb
class Card < ActiveRecord::Base
      has_many :votes
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :comment
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.team = "frilp"
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :card, :counter_cache => true

# rest of your code here
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def growth
  end

  private
  def current_user
    @current_user || User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.reorder("created_at DESC").paginate(:page => params[:page], :per_page => 10)
    @vote = Vote.new(params[:vote])
    @user = current_user
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
    if params[:url]
      @card.url = params[:url]
    end

    if params[:comment]
      @card.poster_comment = params[:comment]
    end
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    url = card_params[:url]

    existing_card = Card.where("url LIKE ?", url).first

    if (existing_card.nil? || existing_card.blank?)
      og_card = OpenGraph.fetch(url)
      @card = Card.new(card_params)
      @card.title = og_card.title if og_card && og_card.has_key?(:title)
      @card.image_url = "http://upload.wikimedia.org/wikipedia/commons/e/eb/Blank.jpg" # Default image
      @card.image_url = og_card.image if og_card && og_card.has_key?(:image)
      @card.description = og_card.description if og_card && og_card.has_key?(:description)
      @card.poster = current_user.name
      @card.poster_uid = current_user.uid
      @card.poster_profile_url = "http://graph.facebook.com/" + @card.poster_uid + "/picture?type=small"
      @card.count_read = 0
      @card.count_liked = 0
      @card.votes_count = 0

      respond_to do |format|
        if @card.save
          format.html { redirect_to @card, notice: 'Card was successfully created.' }
          format.json { render :show, status: :created, location: @card }
        else
          format.html { render :new }
          format.json { render json: @card.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to existing_card, notice: 'Card already exists.' }
        format.json { render :show, status: :created, location: existing_card }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:poster_comment, :title, :description, :url, :poster, :count_read, :count_liked, :category, :image_url)
    end
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  def development
    @cards = Card.where("LOWER(category) LIKE ?", "development").reorder("created_at DESC").paginate(:page => params[:page], :per_page => 10)
  end

  def design
    @cards = Card.where("LOWER(category) LIKE ?", "design").reorder("created_at DESC").paginate(:page => params[:page], :per_page => 10)
  end

  def business
    @cards = Card.where("LOWER(category) LIKE ?", "business").reorder("created_at DESC").paginate(:page => params[:page], :per_page => 10)
  end

  def growth
    @cards = Card.where("LOWER(category) LIKE ?", "growth").reorder("created_at DESC").paginate(:page => params[:page], :per_page => 10)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  # GET /votes/new
  # GET /votes/new.xml
  def new
    @vote = Vote.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @vote }
    end
  end

  # POST /votes
  # POST /votes.xml
  def create

    card_id = params[:vote][:card_id].to_i
    uid = params[:vote][:user_id].to_i

    @extant = Vote.where(:cards_id => card_id, :user_id => uid).first

    last_vote_time = @extant.created_at unless @extant.blank?
    curr_time = Time.now

    if (@extant.nil? || @extant.blank?)
      card = Card.where(:id => card_id).first

      updates_votes_count = card.votes_count + 1

      Card.where(:id => card_id).limit(1).update_all(:votes_count => updates_votes_count)

      @vote = Vote.create(:cards_id => card_id, :user_id  => uid)

      respond_to do |format|
        if @vote.save
          format.js {
            render :js => "
            var upvote_button = document.getElementById('upvote_button');
            upvote_button.parentNode.removeChild(element);
            " }
          format.html { redirect_to :back }
        else
          format.html { redirect_to cards_path }
          format.xml  { render :xml => @vote.errors, :status => :unprocessable_entity }
        end
      end
    else
      render :js =>  "alert('You have already voted for this.');"
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def site_name
    "Tea Stall"
  end

  def site_url
    if Rails.env.production?
      "http://tea-stall.heroku.com"
    else
      "http://localhost:3000"
    end
  end

  def meta_author
    "Anirudh S"
  end

  def meta_description
    "Tea Stall is news source that your team needs"
  end

  def meta_keywords
    "team"
  end

  def full_title(page_title)
    if page_title.empty?
      site_name
    else
      "#{page_title} | #{site_name}"
    end
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/feed_helper.rb
module FeedHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.label :poster_comment %><br>
    <%= f.text_field :poster_comment %>
  </div>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.select :category, options_for_select(%w[Development Design Business Growth]) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<% if current_user %>
<div id="content">
<table class="feed">
  <tbody>
    <% @cards.each do |card| %>
      <tr>
      <div class="post">

        <div class="card">
          <dl>
            <%= image_tag card.poster_profile_url, :id => "profile_pic" %>
            <dt><%= card.poster %></dt>
            <dd><%= link_to time_ago_in_words(card.updated_at) + " ago", card, :target => "_blank" %></dd>
          </dl>
          <dl>
            <dd><%= truncate(strip_tags(card.poster_comment), :length => 140) %></dd>
          </dl>
          <dl>
            <dt><%= link_to truncate(strip_tags(card.url), :length => 120), card.url, :target => "_blank" %></dd>
          </dl>
          <dl>
            <%=link_to (image_tag card.image_url, :width => "100%", :crop => :fill), card.url, :target => "_blank" %>
            <dt><%=link_to (truncate(strip_tags(card.title), :length => 120)), card.url, :target => "_blank" %></dt>
            <dd><%=link_to (truncate(strip_tags(card.description), :length => 300)), card.url, :target => "_blank" %></dd>
          </dl>

          <dl>
            <% vote_exists = Vote.where(:cards_id => card.id, :user_id => @user.id).first %>
            <% if (vote_exists.nil? || vote_exists.blank?) %>
              <dd><%= card.votes_count %> people voted for this</dd>
              <!-- dd><%= card.count_read %> People have read this article from this link</dd-->

              <dd><%= button_to 'Vote',
              {:controller => "votes", :action => "create", :vote => {:card_id => card.id, :user_id=> @user.id}},
              :method=>:post, :remote => true, :id => "upvote_button"  %></dd>

            <%else %>
              <% if card.votes_count = 1%>
              <dd>You voted for this</dd>
              <% else %>
              <dd>You and <%= card.votes_count - 1%> people voted for this</dd>
              <% end %>
            <% end %>
          </dl>

          <dl>
            <dd>Category: <%= card.category %></dd>
          </dl>
        </div>
      </div>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @cards %>
<%end%>
</div>

app/views/cards/new.html.erb
<h1>New card</h1>
<div id="content">
  <% if current_user %>
    <%= render 'form' %>
  <% else %>
    <p>You should be signed in to post new cards</p>
  <% end %>


  <%= link_to 'Back', cards_path %>
</div>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>
  <div class="post">
        <!-- td><%= truncate(strip_tags(@card.image_url), :length => 40) %></td -->
        <div class="card">
          <dl>
            <dt><%= @card.poster %></dt>
            <dd><%= truncate(strip_tags(@card.poster_comment), :length => 120) %></dd>
          </dl>
          <dl>
            <dt><%= link_to truncate(strip_tags(@card.url), :length => 80), @card.url, :target => "_blank" %></dd>
          </dl>
          <dl>
            <%= image_tag @card.image_url, :size => "140x140", :crop => :fill %>
            <dt><%= truncate(strip_tags(@card.title), :length => 80) %></dt>
            <dd><%= truncate(strip_tags(@card.description), :length => 300) %></dd>
          </dl>

          <%= @card.count_read %>
          <%= @card.count_liked %>
          <dl>
            <dd>Category: <%= @card.category %></dd>
            <dd><%= link_to time_ago_in_words(@card.updated_at) + " ago", @card, :target => "_blank" %></dd>
          </dl>
        </div>
      </div>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Home', cards_path %>

app/views/feed/business.html.erb
<% if current_user %>
<div id="content">
<table class="feed">
  <tbody>
    <% @cards.each do |card| %>
      <tr>
      <div class="post">

        <div class="card">
          <dl>
            <%= image_tag card.poster_profile_url, :id => "profile_pic" %>
            <dt><%= card.poster %></dt>
            <dd><%= link_to time_ago_in_words(card.updated_at) + " ago", card, :target => "_blank" %></dd>
          </dl>
          <dl>
            <dd><%= truncate(strip_tags(card.poster_comment), :length => 140) %></dd>
          </dl>
          <dl>
            <dt><%= link_to truncate(strip_tags(card.url), :length => 80), card.url, :target => "_blank" %></dd>
          </dl>
          <dl>
            <%= image_tag card.image_url, :width => "100%", :crop => :fill %>
            <dt><%= truncate(strip_tags(card.title), :length => 80) %></dt>
            <dd><%= truncate(strip_tags(card.description), :length => 300) %></dd>
          </dl>

          <dl>
            <dd>Category: <%= card.category %></dd>

          </dl>
        </div>
      </div>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @cards %>
<%end%>
</div>

app/views/feed/design.html.erb
<% if current_user %>
<div id="content">
<table class="feed">
  <tbody>
    <% @cards.each do |card| %>
      <tr>
      <div class="post">

        <div class="card">
          <dl>
            <%= image_tag card.poster_profile_url, :id => "profile_pic" %>
            <dt><%= card.poster %></dt>
            <dd><%= link_to time_ago_in_words(card.updated_at) + " ago", card, :target => "_blank" %></dd>
          </dl>
          <dl>
            <dd><%= truncate(strip_tags(card.poster_comment), :length => 140) %></dd>
          </dl>
          <dl>
            <dt><%= link_to truncate(strip_tags(card.url), :length => 80), card.url, :target => "_blank" %></dd>
          </dl>
          <dl>
            <%= image_tag card.image_url, :width => "100%", :crop => :fill %>
            <dt><%= truncate(strip_tags(card.title), :length => 80) %></dt>
            <dd><%= truncate(strip_tags(card.description), :length => 300) %></dd>
          </dl>

          <dl>
            <dd>Category: <%= card.category %></dd>

          </dl>
        </div>
      </div>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @cards %>
<%end%>
</div>

app/views/feed/development.html.erb
<% if current_user %>
<div id="content">
<table class="feed">
  <tbody>
    <% @cards.each do |card| %>
      <tr>
      <div class="post">

        <div class="card">
          <dl>
            <%= image_tag card.poster_profile_url, :id => "profile_pic" %>
            <dt><%= card.poster %></dt>
            <dd><%= link_to time_ago_in_words(card.updated_at) + " ago", card, :target => "_blank" %></dd>
          </dl>
          <dl>
            <dd><%= truncate(strip_tags(card.poster_comment), :length => 140) %></dd>
          </dl>
          <dl>
            <dt><%= link_to truncate(strip_tags(card.url), :length => 80), card.url, :target => "_blank" %></dd>
          </dl>
          <dl>
            <%= image_tag card.image_url, :width => "100%", :crop => :fill %>
            <dt><%= truncate(strip_tags(card.title), :length => 80) %></dt>
            <dd><%= truncate(strip_tags(card.description), :length => 300) %></dd>
          </dl>

          <dl>
            <dd>Category: <%= card.category %></dd>

          </dl>
        </div>
      </div>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @cards %>
<%end%>
</div>

app/views/feed/growth.html.erb
<% if current_user %>
<div id="content">
<table class="feed">
  <tbody>
    <% @cards.each do |card| %>
      <tr>
      <div class="post">

        <div class="card">
          <dl>
            <%= image_tag card.poster_profile_url, :id => "profile_pic" %>
            <dt><%= card.poster %></dt>
            <dd><%= link_to time_ago_in_words(card.updated_at) + " ago", card, :target => "_blank" %></dd>
          </dl>
          <dl>
            <dd><%= truncate(strip_tags(card.poster_comment), :length => 140) %></dd>
          </dl>
          <dl>
            <dt><%= link_to truncate(strip_tags(card.url), :length => 80), card.url, :target => "_blank" %></dd>
          </dl>
          <dl>
            <%= image_tag card.image_url, :width => "100%", :crop => :fill %>
            <dt><%= truncate(strip_tags(card.title), :length => 80) %></dt>
            <dd><%= truncate(strip_tags(card.description), :length => 300) %></dd>
          </dl>

          <dl>
            <dd>Category: <%= card.category %></dd>

          </dl>
        </div>
      </div>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @cards %>
<%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, inital-scale=1.0">
  <meta name="description" content="<%= meta_description %>">
  <meta name="author" content="<%= meta_author %>">
  <meta name="Keywords" content="<%= meta_keywords %>">
  <meta http-equiv="refresh" content="300" />

  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <a href="#Top"></a>
</head>
<body>

<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon"></span>
        <span class="icon"></span>
        <span class="icon"></span>
      </button>
      <%= link_to site_name, site_url, :class => "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "All", root_path %></li>
        <li class="<%= 'active' if current_page?(feed_development_path) %>"><%= link_to "Development", feed_development_path %></li>
        <li class="<%= 'active' if current_page?(feed_design_path) %>"><%= link_to "Design", feed_design_path %></li>
        <li class="<%= 'active' if current_page?(feed_business_path) %>"><%= link_to "Business", feed_business_path %></li>
        <li class="<%= 'active' if current_page?(feed_growth_path) %>"><%= link_to "Growth", feed_growth_path %></li>
        <li><a href="javascript:window.location=%22http://localhost:3000/cards/new?url=%22+encodeURIComponent(document.location)+%22&amp;comment=%22+encodeURIComponent(document.title)">
    Add bookmarklet</a></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <li class="<%= 'active' if current_page?(new_card_path) %>"><%= link_to 'New Card', new_card_path %>
        <% if current_user %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name%></a>
          <ul class="dropdown-menu">
            <li><a href="#">Account Settings</a></li>
            <li class="divider"></li>
            <li><a href="#">User stats</a></li>
            <li class="divider"></li>
            <li><a href="#">Messages </a></li>
            <li class="divider"></li>
            <li><a href="#">Favourites Cards </span></a></li>
            <li class="divider"></li>
            <li><%= link_to "Sign out", signout_path, id: "sign_out" %></span></li>
          </ul>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

  <div class="container" id="content">
    <% if current_user %>

    <div id="user-widget">

    </div-->

    <%= yield %>

    <!-- div id="footer">
      <hr>
        <p class="pull-right">
          <%= link_to '<span class="glyphicon-class glyphicon glyphicon-chevron-up"></span> Back to top'.html_safe, '#Top' %>
        </p>
        <p>
          <%= Time.now.year %> <%= site_name %>
        </p>
    </div-->
    <% else %>
    <div class="container">
      <div class="row">
        <form class="form-signin mg-btm">
          <h3 class="heading-desc">Login to TeaStall</h3>
            <div class="social-box">
              <div class="row mg-btm">
                <div class="col-md-12">
                    <a href="/auth/facebook" class="btn btn-primary btn-block">Login with Facebook</a>
                </div>
              </div>
            </div>
          </div>
      </form>
  </div>
</div>
  <% end %>
  </div>

</body>
</html>

app/views/pages/all.html.erb
<h1>News Feed</h1>

<div id="content">
<%= link_to 'New Card', new_card_path %>

<table class="feed">
  <tbody>
    <% @cards.each do |card| %>
      <tr>
      <div class="post">

        <!-- td><%= truncate(strip_tags(card.image_url), :length => 40) %></td -->
        <div class="card">
          <dl>
            <dt><%= card.poster %></dt>
            <dd><%= truncate(strip_tags(card.poster_comment), :length => 120) %></dd>
          </dl>

          <dl>
            <dt><%= truncate(strip_tags(card.title), :length => 80) %></dt>
            <dd><%= truncate(strip_tags(card.description), :length => 300) %></dd>
            <dd><%= link_to truncate(strip_tags(card.url), :length => 40), card.url, :target => "_blank" %></dd>
          </dl>


        <%= card.count_read %>
        <%= card.count_liked %>
        <dl>
          <dt>Category: <%= card.category %></dt>
        </dl>

        <%= link_to time_ago_in_words(card.updated_at) + " ago", card, :target => "_blank" %>
        <!--td><%= link_to 'Edit', edit_card_path(card) %></td-->
        <!--td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td-->

        </div>
      </div>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/pages/business.html.erb
<% provide(:title, "Business news") %>
<h1>Business</h1>
<p>Find me in app/views/pages/business.html.erb</p>

app/views/pages/design.html.erb
<% provide(:title, "Design news") %>
<h1>Design</h1>
<p>Find me in app/views/pages/design.html.erb</p>

app/views/pages/development.html.erb
<% provide(:title, "Development news") %>
<h1>Development</h1>
<p>Find me in app/views/pages/development.html.erb</p>

app/views/pages/growth.html.erb
<% provide(:title, "Growth news") %>
<h1>Growth</h1>
<p>Find me in app/views/pages/growth.html.erb</p>

app/views/welcome/index.html.erb
<h2>Hello World</h2>
<p>
  The time is now <%= Time.now %>
</p>